#!/bin/sh
#
# A hook to check that tests always pass before sharing code.
# A non-zero return value will prevent the push operation
#
# Options to run tests, defaults to empty but can be overriden with git config
options=""

# Relocate to the top directory of our project
relative_prefix=$(git rev-parse --show-prefix)
absolute_path=$PWD
cd $(echo "$absolute_path" | sed "s:\(.*\)$relative_prefix:\1:")

# If user provide a specific command to run, use it
cmd=$(git config hooks.prepush.command)
if [ ! -z "$cmd" ]; then
	eval "$cmd"
# Adopt a common strategy based on the project
elif [ -f pom.xml ]; then                         # Maven project
	goals=$(git config hooks.prepush.maven.goal)
	if [ -z "$goals" ]; then
		goals="clean verify"
	fi
	if git config --bool hooks.prepush.maven.offline > /dev/null; then
		options="$options -o"
	fi
	eval "mvn $options $goals"
elif [ -f Gemfile ]; then                         # Ruby on rails project
	if [ -d spec ]; then
		# Run tests with rspec
		eval "bundle exec rspec spec/"
	fi
fi

